### ISSUE TITLE
Doesn't work with FOSS Puppet

### ISSUE THREAD

**Issue by m0dular** [m0dular/ca_extend#2]
Research a way to make this work with the open source version of Puppet.  Lack of `puppet infra` commands is the most obvious obstacle.

**Comment by Sharpie** [comment]
The Tasks and Plans for extending the CA cert, distributing the CA cert, and detecting expired certificates should be usable on FOSS as there is no difference in that functionality between FOSS and PE.

The plan that does a complete infrastructure rebuild to update a cert should not be expected to work on a FOSS install.

**Comment by m0dular** [comment]
Fixed in the `foss` branch.
