### ISSUE TITLE
Release to the forge / migrate to Puppetlabs namespace?

### ISSUE THREAD

**Issue by bastelfreak** [m0dular/ca_extend#5]
Hi,
thanks for the module and the blogpost at https://puppet.com/blog/extend-expiration-date-puppets-certificate-authority-using-bolt. I noticed that the module isn't released to the forge. Is this planned for the future? Maybe even under the Puppetlabs namespace? That would probably increase the visibility and give it a more serious touch?

**Comment by m0dular** [comment]
@bastelfreak No problem!  Thanks for using and making the `openssl` PR; I just merged that.  I'm not sure what the criteria are to publish something under the `puppetlabs` namespace, but I can look into it.  I think it requires a certain amount of coverage and testing that I don't currently have for this module.

**Comment by m0dular** [comment]
I've published this to `puppetlabs-ca_extend` on the Forge.  Thanks for the suggestion!
